### ISSUE TITLE
Adapt to Lua 5.4

### ISSUE THREAD

**Issue by kaklakariada** [toggledbits/LuWS#3]
Hi @toggledbits,
thank you for your library!
We at @exasol plan to use it in a new open source library but we need support for Lua 5.4. This requires replacing the `bit` library with the [bitwise operators](https://www.lua.org/manual/5.4/manual.html#3.4.2) included in Lua 5.4.

We would like to contribute this as a pull request. Are you interested in this? If possible we would also like to add a rockspec file to simplify installation.

**Comment by redcatbear** [comment]
@toggledbits, could you please indicate whether you would be willing to merge a pull-request that adds bitwise operators for Lua 5.4?

**Comment by toggledbits** [comment]
I guess I'd need to see the pull request first. The purpose of a pull request is to start a discussion. But I can say, if the changes would make it not work on earlier versions of Lua, I'd be unlikely to accept it as-is. If it maintains compatibility, then that's probably easy to accept.

**Comment by kaklakariada** [comment]
In order to maintain backward compatibility with older Lua versions while still using bitwise operators we would need to use something like `load()` to execute code containing the bitwise operators, else it would not compile with older Lua versions. The [base64 module](https://github.com/iskolbin/lbase64) uses a [similar workaround](https://github.com/iskolbin/lbase64/blob/master/base64.lua#L48-L50).

However, our runtime does not allow using `load()` and similar functions, so this is not an option for us.

That's why we will continue to use a [modified copy of luws.lua](https://github.com/exasol/exasol-driver-lua/blob/main/src/luasql/exasol/luws.lua).

Thanks again for your very helpful library!
